package com.food.mall.pojo;



import com.food.mall.dto.CategoryODto;
import org.springframework.beans.BeanUtils;

import javax.persistence.Id;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    @Id
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.name
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.type
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.father_id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private Integer fatherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.logo
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.slogan
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private String slogan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cat_image
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private String catImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.bg_color
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private String bgColor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param name the value for category.name
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.type
     *
     * @return the value of category.type
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.type
     *
     * @param type the value for category.type
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.father_id
     *
     * @return the value of category.father_id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public Integer getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.father_id
     *
     * @param fatherId the value for category.father_id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setFatherId(Integer fatherId) {
        this.fatherId = fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.logo
     *
     * @return the value of category.logo
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.logo
     *
     * @param logo the value for category.logo
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.slogan
     *
     * @return the value of category.slogan
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getSlogan() {
        return slogan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.slogan
     *
     * @param slogan the value for category.slogan
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setSlogan(String slogan) {
        this.slogan = slogan == null ? null : slogan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cat_image
     *
     * @return the value of category.cat_image
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getCatImage() {
        return catImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cat_image
     *
     * @param catImage the value for category.cat_image
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setCatImage(String catImage) {
        this.catImage = catImage == null ? null : catImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.bg_color
     *
     * @return the value of category.bg_color
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getBgColor() {
        return bgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.bg_color
     *
     * @param bgColor the value for category.bg_color
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setBgColor(String bgColor) {
        this.bgColor = bgColor == null ? null : bgColor.trim();
    }

    public static CategoryODto category2CategoryODto(Category param){
        if(param == null){
            return null;
        }
        CategoryODto categoryODto = new CategoryODto();
        BeanUtils.copyProperties(param,categoryODto);
        return categoryODto;
    }
}