package com.food.mall.pojo;



import javax.persistence.Id;
import java.util.Date;

public class Items {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    @Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_name
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.cat_id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private Integer catId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.root_cat_id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private Integer rootCatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.sell_counts
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private Integer sellCounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.on_off_status
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private Integer onOffStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.created_time
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.updated_time
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.content
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.id
     *
     * @return the value of items.id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.id
     *
     * @param id the value for items.id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_name
     *
     * @return the value of items.item_name
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_name
     *
     * @param itemName the value for items.item_name
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.cat_id
     *
     * @return the value of items.cat_id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public Integer getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.cat_id
     *
     * @param catId the value for items.cat_id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setCatId(Integer catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.root_cat_id
     *
     * @return the value of items.root_cat_id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public Integer getRootCatId() {
        return rootCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.root_cat_id
     *
     * @param rootCatId the value for items.root_cat_id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setRootCatId(Integer rootCatId) {
        this.rootCatId = rootCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.sell_counts
     *
     * @return the value of items.sell_counts
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public Integer getSellCounts() {
        return sellCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.sell_counts
     *
     * @param sellCounts the value for items.sell_counts
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setSellCounts(Integer sellCounts) {
        this.sellCounts = sellCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.on_off_status
     *
     * @return the value of items.on_off_status
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public Integer getOnOffStatus() {
        return onOffStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.on_off_status
     *
     * @param onOffStatus the value for items.on_off_status
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setOnOffStatus(Integer onOffStatus) {
        this.onOffStatus = onOffStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.created_time
     *
     * @return the value of items.created_time
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.created_time
     *
     * @param createdTime the value for items.created_time
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.updated_time
     *
     * @return the value of items.updated_time
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.updated_time
     *
     * @param updatedTime the value for items.updated_time
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.content
     *
     * @return the value of items.content
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.content
     *
     * @param content the value for items.content
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}