package com.food.mall.pojo;



import javax.persistence.Id;
import java.util.Date;

public class UserAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    @Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.user_id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.receiver
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.mobile
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.province
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.city
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.district
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.detail
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.extand
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private String extand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.is_default
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private Integer isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.created_time
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.updated_time
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.id
     *
     * @return the value of user_address.id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.id
     *
     * @param id the value for user_address.id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.user_id
     *
     * @return the value of user_address.user_id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.user_id
     *
     * @param userId the value for user_address.user_id
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.receiver
     *
     * @return the value of user_address.receiver
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.receiver
     *
     * @param receiver the value for user_address.receiver
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.mobile
     *
     * @return the value of user_address.mobile
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.mobile
     *
     * @param mobile the value for user_address.mobile
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.province
     *
     * @return the value of user_address.province
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.province
     *
     * @param province the value for user_address.province
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.city
     *
     * @return the value of user_address.city
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.city
     *
     * @param city the value for user_address.city
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.district
     *
     * @return the value of user_address.district
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.district
     *
     * @param district the value for user_address.district
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.detail
     *
     * @return the value of user_address.detail
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.detail
     *
     * @param detail the value for user_address.detail
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.extand
     *
     * @return the value of user_address.extand
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public String getExtand() {
        return extand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.extand
     *
     * @param extand the value for user_address.extand
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setExtand(String extand) {
        this.extand = extand == null ? null : extand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.is_default
     *
     * @return the value of user_address.is_default
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.is_default
     *
     * @param isDefault the value for user_address.is_default
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.created_time
     *
     * @return the value of user_address.created_time
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.created_time
     *
     * @param createdTime the value for user_address.created_time
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.updated_time
     *
     * @return the value of user_address.updated_time
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.updated_time
     *
     * @param updatedTime the value for user_address.updated_time
     *
     * @mbggenerated Wed Oct 14 22:42:35 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}