server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://172.17.0.1:3306/food_mall?useUnicode=true&useSSL=false&characterEncoding=UTF-8&autoReconnect=true
    driverClassName: com.mysql.jdbc.Driver
    password: 123456
    username: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000     # 文件上传大小限制为500kb
      max-request-size: 512000  # 请求大小限制为500kb

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.food.mall.pojo       # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件

app:
  serverUrl: http://172.17.0.1:80                                 # 接口服务接口地址
  paymentServerUrl: http://192.168.1.3:8089                        # 支付中心服务地址
  shopServerUrl: http://localhost:8080/foodie-shop/                # 门户网站地址
  centerServerUrl: http://localhost:8080/foodie-center/            # 用户中心地址
